# save DataFrame to CSV

In [1]:
import pandas as pd
print(f'pandas version: {pd.__version__}')

pandas version: 1.1.3

In [19]:
df=pd.read_csv('https://github.com/prasertcbs/basic-dataset/raw/master/country_region.csv')
df

               country alpha2 alpha3   region           subregion
0          Afghanistan     AF    AFG     Asia       Southern Asia
1        Åland Islands     AX    ALA   Europe     Northern Europe
2              Albania     AL    ALB   Europe     Southern Europe
3              Algeria     DZ    DZA   Africa     Northern Africa
4       American Samoa     AS    ASM  Oceania           Polynesia
..                 ...    ...    ...      ...                 ...
244  Wallis and Futuna     WF    WLF  Oceania           Polynesia
245     Western Sahara     EH    ESH   Africa     Northern Africa
246              Yemen     YE    YEM     Asia        Western Asia
247             Zambia     ZM    ZMB   Africa  Sub-Saharan Africa
248           Zimbabwe     ZW    ZWE   Africa  Sub-Saharan Africa

[249 rows x 5 columns]

In [20]:
df.to_csv('data/demo1.csv')

In [26]:
!cat data/demo1.csv

'cat' is not recognized as an internal or external command,
operable program or batch file.

In [5]:
df.to_csv('data/demo2.csv', index_label='id')

In [28]:
!cat data/demo2.csv

The syntax of the command is incorrect.

In [7]:
df.to_csv('data/demo3.csv', index=False)

In [30]:
!type data/demo3.csv

The syntax of the command is incorrect.

In [9]:
df.columns

Index(['country', 'alpha2', 'alpha3', 'region', 'subregion'], dtype='object')

In [10]:
df.to_csv('data/demo4.csv', index=False, columns=['country', 'alpha2', 'region'])

In [11]:
!cat data/demo4.csv

'cat' is not recognized as an internal or external command,
operable program or batch file.

In [12]:
df[df.region=='Asia']

,country,alpha2,alpha3,region,subregion
0,Afghanistan,AF,AFG,Asia,Southern Asia
11,Armenia,AM,ARM,Asia,Western Asia
15,Azerbaijan,AZ,AZE,Asia,Western Asia
17,Bahrain,BH,BHR,Asia,Western Asia
18,Bangladesh,BD,BGD,Asia,Southern Asia
25,Bhutan,BT,BTN,Asia,Southern Asia
33,Brunei Darussalam,BN,BRN,Asia,South-eastern Asia
38,Cambodia,KH,KHM,Asia,South-eastern Asia
45,China,CN,CHN,Asia,Eastern Asia
58,Cyprus,CY,CYP,Asia,Western Asia
81,Georgia,GE,GEO,Asia,Western Asia
99,Hong Kong,HK,HKG,Asia,Eastern Asia
102,India,IN,IND,Asia,Southern Asia
103,Indonesia,ID,IDN,Asia,South-eastern Asia
104,Iran (Islamic Republic of),IR,IRN,Asia,Southern Asia
105,Iraq,IQ,IRQ,Asia,Western Asia
108,Israel,IL,ISR,Asia,Western Asia
111,Japan,JP,JPN,Asia,Eastern Asia
113,Jordan,JO,JOR,Asia,Western Asia
114,Kazakhstan,KZ,KAZ,Asia,Central Asia
117,Korea (Democratic People's Republic of),KP,PRK,Asia,Eastern Asia
118,Korea (Republic of),KR,KOR,Asia,Eastern Asia
119,Kuwait,KW,KWT,Asia,Western Asia
120,Kyrgyzstan,KG,KGZ,Asia,Central Asia
121,Lao People's Democratic Republic,LA,LAO,Asia,South-eastern Asia
123,Lebanon,LB,LBN,Asia,Western Asia
130,Macao,MO,MAC,Asia,Eastern Asia
134,Malaysia,MY,MYS,Asia,South-eastern Asia
135,Maldives,MV,MDV,Asia,Southern Asia
147,Mongolia,MN,MNG,Asia,Eastern Asia
152,Myanmar,MM,MMR,Asia,South-eastern Asia
155,Nepal,NP,NPL,Asia,Southern Asia
166,Oman,OM,OMN,Asia,Western Asia
167,Pakistan,PK,PAK,Asia,Southern Asia
169,"Palestine, State of",PS,PSE,Asia,Western Asia
174,Philippines,PH,PHL,Asia,South-eastern Asia
179,Qatar,QA,QAT,Asia,Western Asia
194,Saudi Arabia,SA,SAU,Asia,Western Asia
199,Singapore,SG,SGP,Asia,South-eastern Asia
209,Sri Lanka,LK,LKA,Asia,Southern Asia
216,Syrian Arab Republic,SY,SYR,Asia,Western Asia
217,"Taiwan, Province of China",TW,TWN,Asia,Eastern Asia
218,Tajikistan,TJ,TJK,Asia,Central Asia
220,Thailand,TH,THA,Asia,South-eastern Asia
221,Timor-Leste,TL,TLS,Asia,South-eastern Asia
227,Turkey,TR,TUR,Asia,Western Asia
228,Turkmenistan,TM,TKM,Asia,Central Asia
233,United Arab Emirates,AE,ARE,Asia,Western Asia
238,Uzbekistan,UZ,UZB,Asia,Central Asia
241,Viet Nam,VN,VNM,Asia,South-eastern Asia
246,Yemen,YE,YEM,Asia,Western Asia

In [13]:
df[df.region=='Asia'].to_csv('data/asia.csv', index=False)

In [14]:
!cat data/asia.csv

'cat' is not recognized as an internal or external command,
operable program or batch file.

In [15]:
df.region.unique()

array(['Asia', 'Europe', 'Africa', 'Oceania', 'Americas', nan],
      dtype=object)

In [16]:
df[df.region.notna()].region.unique()

array(['Asia', 'Europe', 'Africa', 'Oceania', 'Americas'], dtype=object)

In [17]:
for r in df[df.region.notna()].region.unique():
    df[df.region == r].to_csv(f'data/{r}.csv', index=False)

In [18]:
!cat data/Europe.csv

'cat' is not recognized as an internal or external command,
operable program or batch file.

In [31]:
!type data/Europe.csv

The syntax of the command is incorrect.